from __future__ import annotations

DEFAULT_DAYS = 1825
DEFAULT_DECK_SIZE = 10000
DEFAULT_LEARN_LIMIT = 10
DEFAULT_REVIEW_LIMIT = 9999
DEFAULT_COST_LIMIT_MINUTES = 720
DEFAULT_SEED = 42
DEFAULT_PRIORITY = "new-first"
DEFAULT_SCHEDULER_PRIORITY = "low_retrievability"
DEFAULT_SHORT_TERM_LOOPS_LIMIT = 10
DEFAULT_END_USER = 10000
